### ISSUE TITLE
Unable to Log in – AntilandAPIError: Unauthorize

### ISSUE THREAD

**Issue by ryan6090** [Calculamatrise/antiland#15]
I'm experiencing an issue when trying to log in using the latest version. When I input my username and password, the following error is outputted in the command console:

Error logging in: AntilandAPIError: unauthorized at file:///C:/Windows/System32/antiland-bot/node_modules/antiland/src/utils/RequestHandler.js:70:11 at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async Client.login (file:///C:/Windows/System32/antiland- bot/node_modules/antiland/src/client/BaseClient.js:414:14)

I also tried using my session token, but I encounter the same error.

I’ve implemented the JS files based on the code you provided. Is there something I might be missing or doing wrong in the login process? Any help would be greatly appreciated.

**Comment by Calculamatrise** [comment]
Could you provide the version you are using as well as the version of Node.js you are currently running, and could you also try logging in on the latest dev release to see if the issue still persists? I've just rewritten the logic that verifies logins and tested it with both user/pass and token login methods. The error message you received, "unauthorized," typically means that your token is invalid, or your username or password is incorrect. Please try logging into the actual app to verify that the token is valid.

**Comment by ryan6090** [comment]
"The issue persists with the current version of the `antiland` library. Here are the details:
**Version of `antiland api `:** latest with you updated changes 
- **Node.js version:** 23.4.0
The error message I received, `unauthorized`, typically indicates an issue with the provided username or password, or that the token is invalid. The developer mentioned that they have rewritten the login verification logic and tested both user/password and token methods on the latest dev release. To further diagnose, they suggested trying to log in using the latest dev release to see if the issue persists.

 I have also verified that the credentials are correct by logging into the actual app. Here’s the updated script:
javascript
```js
import { Client } from 'antiland'; 
const client = new Client({
     username: "bigshow6090",
     password: "Dottie11!!",
 });
 
 client.on('ready', () => {
     console.log(`Logged in as ${client.user.username}!`);
 });
 
 client.login()
     .then(() => {
         console.log("Login successful with username and password!");
     })
     .catch(err => {
         console.error("Error logging in:", err.response?.data || err.message);
     });
```

the example you used on the homepage gives me an error and wont let me  use the script so i went to your wiki and incorporated that login method

**Comment by Calculamatrise** [comment]
Thank you for providing me with the code. Now I can easily point out where you went wrong. I have not implemented a way to login via the client options. The login data/token must be passed through the login method parameters, not the client constructor.
